// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function Greet(arg1:string):Promise<string>;

export function MessageDialog(arg1:string,arg2:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function SetExpiry(arg1:engine.Options):Promise<string>;
