// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {context} from '../models';

export function BeforeSetExpiry(arg1:engine.Options):Promise<string>;

export function GetMachineCode():Promise<string>;

export function GetTitleWithRegStatus():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsRegistered():Promise<boolean>;

export function ListPDFInDir(arg1:string):Promise<Array<string>>;

export function MessageDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OpenDirectoryAndListFiles():Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function Register(arg1:string):Promise<string>;

export function SetExpiry(arg1:engine.Options):Promise<string>;
