// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MessageDialog(arg1, arg2) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function SetExpiry(arg1) {
  return window['go']['main']['App']['SetExpiry'](arg1);
}
