// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMachineCode() {
  return window['go']['main']['App']['GetMachineCode']();
}

export function GetTitleWithRegStatus() {
  return window['go']['main']['App']['GetTitleWithRegStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRegistered() {
  return window['go']['main']['App']['IsRegistered']();
}

export function ListPDFInDir(arg1) {
  return window['go']['main']['App']['ListPDFInDir'](arg1);
}

export function MessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2, arg3);
}

export function OnDomReady(arg1) {
  return window['go']['main']['App']['OnDomReady'](arg1);
}

export function OpenDirectoryAndListFiles() {
  return window['go']['main']['App']['OpenDirectoryAndListFiles']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function SetExpiry(arg1) {
  return window['go']['main']['App']['SetExpiry'](arg1);
}
